apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiosk-backend-media-pv
  labels:
    app.kubernetes.io/name: kiosk-backend-media
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zfs
  nfs:
    server: 192.168.11.16
    path: /srv/nfs/kubernetes/kiosk-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiosk-backend-media
  namespace: kiosk-screen
  labels:
    app.kubernetes.io/name: kiosk-backend-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: kiosk-backend-media-pv
