apiVersion: v1
kind: Secret
metadata:
  name: kiosk-secrets
  namespace: kiosk-screen
  labels:
    app.kubernetes.io/name: kiosk
type: Opaque
stringData:
  DATABASE_URL: "fake_secret"
  SESSION_SECRET: "fake_secret"
  BOOTSTRAP_ADMIN_EMAIL: "fake_secret"
  BOOTSTRAP_ADMIN_PASSWORD : "fake_secret"
  REDIS_URL: "fake_secret"
